/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Course.CourseOffering;
import Business.Course.Enrollment;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chinm
 */
public class CourseRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseRegistrationJPanel
     */
    private ArrayList<CourseOffering> allOfferings;
    private StudentProfile student;
    private JPanel cardSequencePanel;

    public CourseRegistrationJPanel(JPanel cardSequencePanel, StudentProfile  student) {
        initComponents();
        this.student = student;
        this.cardSequencePanel = cardSequencePanel;
        this.allOfferings = new ArrayList<>();
        populateTable(allOfferings);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldRCCourseName = new javax.swing.JTextField();
        fieldRCId = new javax.swing.JTextField();
        fieldRCFacultyName = new javax.swing.JTextField();
        btnSearchByCourseName = new javax.swing.JButton();
        btnSearchById = new javax.swing.JButton();
        btnSearchByFacultyName = new javax.swing.JButton();
        btnEnroll = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(189, 221, 252));

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CourseID", "Title", "Description", "Schedule", "Capacity", "Faculty", "EnrollmentOpen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourses);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Register for Courses");

        jLabel3.setText("Search by faculty name");

        jLabel4.setText("Search by course name");

        btnSearchByCourseName.setText("Search");
        btnSearchByCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByCourseNameActionPerformed(evt);
            }
        });

        btnSearchById.setText("Search");
        btnSearchById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByIdActionPerformed(evt);
            }
        });

        btnSearchByFacultyName.setText("Search");
        btnSearchByFacultyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByFacultyNameActionPerformed(evt);
            }
        });

        btnEnroll.setText("Enroll ");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel2.setText("Search by ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(402, 402, 402)
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(fieldRCId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSearchById))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(fieldRCFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSearchByFacultyName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(fieldRCCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSearchByCourseName)
                        .addGap(168, 168, 168)
                        .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnback))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(fieldRCId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchById))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fieldRCFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByFacultyName))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(fieldRCCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByCourseName)
                    .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchByCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchByCourseNameActionPerformed

    private void btnSearchByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByIdActionPerformed
        String id = fieldRCId.getText();
        ArrayList<CourseOffering> results = new ArrayList<>();
        for (CourseOffering co : allOfferings) {
            if (co.getCourse().getCourseId().equalsIgnoreCase(id)) {
                results.add(co);
            }
        }
        populateTable(results);

    }//GEN-LAST:event_btnSearchByIdActionPerformed

    private void btnSearchByFacultyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByFacultyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchByFacultyNameActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed

        CardLayout layout = (CardLayout) cardSequencePanel.getLayout();
        layout.show(cardSequencePanel, "StudentWorkAreaJPanel");

    }//GEN-LAST:event_btnbackActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        int selectedRow = tblCourses.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }

        CourseOffering co = allOfferings.get(selectedRow);

        if (!co.isEnrollmentOpen()) {
            JOptionPane.showMessageDialog(this, "Enrollment not activated by faculty.");
            return;
        }

        int currentCredits = student.getTranscript().getCurrentTermCredits(co.getSemester());
        if (currentCredits + co.getCourse().getCreditHours() > 8) {
            JOptionPane.showMessageDialog(this, "You cannot take more than 8 credits this semester.");
            return;
        }

        Enrollment e = new Enrollment(student, co);
        if (co.enrollStudent(e)) {
            JOptionPane.showMessageDialog(this, "Enrolled successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Enrollment failed (capacity full).");
        }

    }//GEN-LAST:event_btnEnrollActionPerformed

    private void populateTable(ArrayList<CourseOffering> offerings) {
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
        model.setRowCount(0);

        for (CourseOffering co : offerings) {
            model.addRow(new Object[]{
                co.getCourse().getCourseId(),
                co.getCourse().getCourseName(),
                co.getFaculty().getPerson().getPersonId(),
                co.getCourse().getCreditHours(),
                co.getCapacity(),
                co.isEnrollmentOpen() ? "Open" : "Closed"
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnSearchByCourseName;
    private javax.swing.JButton btnSearchByFacultyName;
    private javax.swing.JButton btnSearchById;
    private javax.swing.JButton btnback;
    private javax.swing.JTextField fieldRCCourseName;
    private javax.swing.JTextField fieldRCFacultyName;
    private javax.swing.JTextField fieldRCId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables
}
